#!/usr/bin/env ruby

root_dir = File.expand_path("#{File.expand_path("#{File.dirname(__FILE__)}")}/..")

ordered_js_files = [
  "/javascripts/underscore.js"
]

js_files = (ordered_js_files + Dir["#{root_dir}/public/javascripts/**/*.js"].map do |path|
  File.expand_path(path).gsub("#{root_dir}/public", "")
end).uniq

args = [
  "--framework-path=#{root_dir}/spec/screw-unit/lib",
  "--javascript-files=#{js_files.join(",")},/specs/spec_helper.js"
] + ARGV
exec "screw-unit-server #{args.join(" ")}"