#!/usr/bin/env ruby

root_dir = File.expand_path("#{File.expand_path("#{File.dirname(__FILE__)}")}/..")

require "rubygems"
require "nokogiri"

doc = Nokogiri::HTML(File.read("#{root_dir}/public/index.html"))
js_files = doc.css("script").map do |script|
  script["src"]
end.compact

args = [
  "--framework-path=#{root_dir}/spec/screw-unit/lib",
  "--javascript-files=#{js_files.join(",")},/specs/spec_helper.js"
] + ARGV
exec "screw-unit-server #{args.join(" ")}"